# Generated by Django 4.2.2 on 2023-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeRequirements',
            new_name='RecipeRequirement',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
