# Generated by Django 4.2.2 on 2023-10-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeTable',
        ),
    ]
