# Generated by Django 4.2.2 on 2023-06-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_reciperequirements_reciperequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
