# Generated by Django 4.2.2 on 2023-11-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_reciperequirement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cogs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
